- name: Deploys VM based on cloud image
  hosts: localhost
  gather_facts: yes
#  become: yes
  vars:
    pool_dir: "/var/lib/libvirt/images"
    vm: test-vm
    vcpus: 2
    ram_mb: 2048
    cleanup: no
    net: default
    ssh_pub_key: "/root/.ssh/id_rsa.pub"

  tasks:
    - name: KVM Provision role
      include_role:
        name: kvm_provision
      vars:
        libvirt_pool_dir: "{{ pool_dir }}"
        vm_name: "{{ vm }}"
        vm_vcpus: "{{ vcpus }}"
        vm_ram_mb: "{{ ram_mb }}"
        vm_net: "{{ net }}"
        cleanup_tmp: "{{ cleanup }}"
        ssh_key: "{{ ssh_pub_key }}"

#- name: Configure VMs network
#  hosts: all
#  gather_facts: yes
#  become: yes
#  vars:
#    vm: test-vm
#    s1mme: s1mme-ip
#    s11: s11-ip

#  tasks:
#    - name: Network configuration role
#      include_role:
#        name: network_configs
#      vars:
#        vm_name: "{{ vm }}"
#        s1mme_ip: "{{ s1mme }}"
#        s11_ip: "{{ s11 }}"

